# Generated by Django 2.2.6 on 2021-08-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210826_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsfromus',
            name='question_no',
        ),
    ]
