# Generated by Django 2.2.6 on 2021-08-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_questionsfromus_question_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsfromus',
            name='question_no',
            field=models.IntegerField(null=True),
        ),
    ]
