# Generated by Django 2.2.6 on 2021-08-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_questionsfromus_question_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersforfromus',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='answersforfromus',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
