# Generated by Django 3.2.6 on 2021-08-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210826_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersforfromself',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='answersforfromself',
            name='updated_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='answersforfromus',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='answersforfromus',
            name='updated_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
