# Generated by Django 3.2.6 on 2021-08-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210827_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersforfromus',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='answersforfromus',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
