# Generated by Django 3.2.6 on 2021-08-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210827_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersforfromself',
            name='created_at_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='answersforfromus',
            name='created_at_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
