# Generated by Django 3.2.6 on 2021-08-28 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210828_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsfromself',
            name='this_user',
        ),
    ]
