# Generated by Django 3.2.6 on 2021-08-28 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_questionsfromself_this_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionsfromself',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='questionsfromus',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
