# Generated by Django 3.2.6 on 2021-08-29 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_auto_20210828_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedanswers',
            name='bookmarker',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savedanswers', to=settings.AUTH_USER_MODEL),
        ),
    ]
