# Generated by Django 3.2.6 on 2021-09-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_savedanswers_bookmarker'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(blank=True, max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='random_images')),
            ],
        ),
    ]
