# Generated by Django 3.2.6 on 2021-09-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210905_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersforfromself',
            name='answer_no',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='answersforfromus',
            name='answer_no',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
