# Generated by Django 3.2.6 on 2021-09-04 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210905_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedanswers',
            name='ans_no',
        ),
        migrations.AddField(
            model_name='savedanswers',
            name='ans_self_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savedanswers', to='main.answersforfromself'),
        ),
        migrations.AddField(
            model_name='savedanswers',
            name='ans_us_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savedanswers', to='main.answersforfromus'),
        ),
    ]
