# Generated by Django 3.2.6 on 2021-10-21 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0021_commentansus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentansus',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentusauthor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CommentAnsSelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('body', models.CharField(blank=True, max_length=2000, null=True)),
                ('ans', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentansself', to='main.answersforfromself')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentselfauthor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
