# Generated by Django 3.2.6 on 2021-10-21 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_userinfo_profile_image'),
        ('main', '0022_auto_20211021_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentansself',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentselfauthor', to='member.userinfo'),
        ),
        migrations.AlterField(
            model_name='commentansus',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentusauthor', to='member.userinfo'),
        ),
    ]
