# Generated by Django 3.2.6 on 2021-11-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20211021_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersforfromself',
            name='author_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answersforfromus',
            name='author_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answersforfromself',
            name='updated_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='answersforfromus',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
