# Generated by Django 3.2.6 on 2022-02-13 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersforfromus',
            name='from_today_ques',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='likes',
            name='ans_self_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likesSelf', to='main.answersforfromself'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='ans_us_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likesUs', to='main.answersforfromus'),
        ),
    ]
