# Generated by Django 3.2.6 on 2022-04-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrysRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
