# Generated by Django 3.2.6 on 2021-10-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0004_alter_userinfo_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('pass_condition', models.IntegerField()),
                ('participant', models.ManyToManyField(related_name='participant', to='member.UserInfo')),
                ('passed', models.ManyToManyField(related_name='passed', to='member.UserInfo')),
            ],
        ),
    ]
