# Generated by Django 3.2.6 on 2021-12-04 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsFromOthers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_img')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_at_time', models.DateTimeField(auto_now_add=True)),
                ('questioner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questionfromothers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnswersForFromOthers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=10000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='answer_img')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_at_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answersforfromothers', to=settings.AUTH_USER_MODEL)),
                ('question_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answersforfromothers', to='questionsquare.questionsfromothers')),
            ],
        ),
    ]
