# Generated by Django 3.2.6 on 2021-08-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='persona_type',
            field=models.CharField(max_length=50),
        ),
    ]
