# Generated by Django 3.2.6 on 2021-09-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20210902_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_image',
            field=models.ImageField(default='default_psa.jpg', null=True, upload_to='profile_images'),
        ),
    ]
